name:                int
version:             0.1.0.0
github:              "githubuser/int"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2026 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/int#readme>

dependencies:
- base >= 4.7 && < 5
- hasktorch
- nlp-tools
- hasktorch-tools
- gnuplot
- cassava
- vector
- bytestring

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  int-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - int
  sess3:
    main:                LinearRegression.hs
    source-dirs:         Session3
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - int
  sess3.2:
    main:                GraduateAdmissionLinear.hs
    source-dirs:         Session3
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - int
  
  sess4:
    main:                PerceptronAndGate.hs
    source-dirs:         Session4
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is PerceptronAndGate
    dependencies:
    - int

  xor2:
    main:                xor2.hs
    source-dirs:         Session4
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Xor2
    dependencies:
    - int

  sess5:
    main:                Evaluation.hs
    source-dirs:         Session5
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Evaluation
    dependencies:
    - int

  admit:
    main:                Admit.hs
    source-dirs:         Session5
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Admit
    dependencies:
    - int

  bow:
    main:                bow.hs
    source-dirs:         Session6
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Bow
    dependencies:
    - int
    - utf8-string
    - bytestring
    - containers
    - split

  rnn:
    main:                RNN.hs
    source-dirs:         Session7
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is RNN
    dependencies:
    - int
    - utf8-string
    - bytestring
    - containers
    - split
    - aeson
    - mtl

  lstm:
    main:                LSTM.hs
    source-dirs:         FinalSession
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is LSTM
    dependencies:
    - int
    - utf8-string
    - bytestring
    - containers
    - split
    - aeson
    - mtl

  good:
    main:                good.hs
    source-dirs:         Session6
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Good
    dependencies:
    - int
    - utf8-string
    - bytestring
    - containers

  session-3-multiple-regression:
    main:                MultipleRegression.hs
    source-dirs:         Session3
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - int
  

tests:
  int-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - int
